"""update models

Revision ID: 960ba785b652
Revises: 9ef44674d151
Create Date: 2024-07-31 14:56:42.426007

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "960ba785b652"
down_revision = "9ef44674d151"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
